version: '3.8'

services: 
  psqldb:
    image: postgres:latest
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_USER=$PGUSER
      - POSTGRES_PASSWORD=$PGPASSWORD
      - POSTGRES_DB=$PGDATABASE
      - POSTGRES_HOST=$PGHOST
      - POSTGRES_PORT=$PGPORT
    expose:
      - "$PGPORT"
    volumes:
      - ./docker/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "postgres"]
      interval: 5s
      retries: 3
  server:
    depends_on:
      psqldb:
        condition: service_healthy
    build: server/
    restart: always
    env_file: ./.env
    ports:
      - "$SERVER_LOCAL_PORT:$SERVER_LOCAL_PORT"
    environment:
      - PGUSER=$PGUSER
      - PGPASSWORD=$PGPASSWORD
      - PGDATABASE=$PGDATABASE
      - PGHOST=$PGHOST
      - PGPORT=$PGPORT
      - PORT=$SERVER_LOCAL_PORT
    volumes:
      - ./output.log:/src/server/output.log
      - ./error.log:/src/server/error.log
  client:
    depends_on:
      - server
    build: 
      context: client/
      args: 
        REACT_APP_SERVER_LOCAL_PORT: $SERVER_LOCAL_PORT
    restart: always
    ports:
      - "$CLIENT_DOCKER_PORT:$CLIENT_DOCKER_PORT"
    volumes:
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./docker/certbot/www:/var/www/certbot/
      - ./docker/certbot/conf/:/etc/nginx/ssl/
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./docker/certbot/www/:/var/www/certbot/
      - ./docker/certbot/conf/:/etc/letsencrypt/